# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        none

# Setup
title:            Minjung Kim
tagline:          Honors Portfolio
url:              http://minjung-kim.github.io
paginate:         1
baseurl:          /
author:
  name:           Minjung Kim
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/minjung-kim/minjung-kim.github.io